[package]
name = "l4-load-balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
ctrlc = "3.5.2"
mio = { version = "1.2.2", features = ["os-poll", "net"] }
rlimit = "0.11.0"
serde = { version = "1.0.229", features = ["derive"] }
slab = "0.4.12"
toml = "1.1.5"
